//
//  FacebookButton.swift
//
//  Created on Feb 20, 2018.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

import UIKit



class FacebookButton: NSObject {
    
    
    //MARK: - Canvas Drawings
    
    /// Page 1
    
    class func drawDesktop(frame targetFrame: CGRect = CGRect(x: 0, y: 0, width: 1024, height: 1024), resizing: ResizingBehavior = .aspectFit) {
        /// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        /// Resize to Target Frame
        context.saveGState()
        let resizedFrame = resizing.apply(rect: CGRect(x: 0, y: 0, width: 1024, height: 1024), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 1024, y: resizedFrame.height / 1024)
        
        /// ShareButton
        do {
            context.saveGState()
            context.translateBy(x: 397, y: 338)
            
            /// Circle
            let circle = UIBezierPath(roundedRect: CGRect(x: 0, y: 0, width: 80, height: 80), cornerRadius: 100)
            context.saveGState()
            context.saveGState()
            circle.addClip()
            context.drawLinearGradient(CGGradient(colorsSpace: nil, colors: [
                        UIColor(hue: 0.094, saturation: 0.692, brightness: 1, alpha: 1).cgColor,
                        UIColor(hue: 0.092, saturation: 0.691, brightness: 1, alpha: 1).cgColor,
                        UIColor(hue: 0.084, saturation: 0.689, brightness: 1, alpha: 1).cgColor,
                        UIColor(hue: 0.004, saturation: 0.661, brightness: 0.996, alpha: 1).cgColor,
                    ] as CFArray, locations: [0, 0, 0.1, 1])!,
                start: CGPoint(x: -21.07, y: -18.99),
                end: CGPoint(x: 64.72, y: 72.44),
                options: [.drawsBeforeStartLocation, .drawsAfterEndLocation])
            context.restoreGState()
            context.restoreGState()
            
            /// Shape
            let shape = UIBezierPath()
            shape.move(to: CGPoint(x: 24.17, y: 22.53))
            shape.addCurve(to: CGPoint(x: 21.01, y: 23.76), controlPoint1: CGPoint(x: 22.94, y: 22.53), controlPoint2: CGPoint(x: 21.85, y: 23.01))
            shape.addLine(to: CGPoint(x: 9.52, y: 17.12))
            shape.addCurve(to: CGPoint(x: 9.67, y: 16), controlPoint1: CGPoint(x: 9.6, y: 16.75), controlPoint2: CGPoint(x: 9.67, y: 16.38))
            shape.addCurve(to: CGPoint(x: 9.52, y: 14.88), controlPoint1: CGPoint(x: 9.67, y: 15.62), controlPoint2: CGPoint(x: 9.6, y: 15.25))
            shape.addLine(to: CGPoint(x: 20.88, y: 8.3))
            shape.addCurve(to: CGPoint(x: 24.17, y: 9.6), controlPoint1: CGPoint(x: 21.75, y: 9.1), controlPoint2: CGPoint(x: 22.89, y: 9.6))
            shape.addCurve(to: CGPoint(x: 29, y: 4.8), controlPoint1: CGPoint(x: 26.84, y: 9.6), controlPoint2: CGPoint(x: 29, y: 7.46))
            shape.addCurve(to: CGPoint(x: 24.17, y: 0), controlPoint1: CGPoint(x: 29, y: 2.14), controlPoint2: CGPoint(x: 26.84, y: 0))
            shape.addCurve(to: CGPoint(x: 19.33, y: 4.8), controlPoint1: CGPoint(x: 21.49, y: 0), controlPoint2: CGPoint(x: 19.33, y: 2.14))
            shape.addCurve(to: CGPoint(x: 19.48, y: 5.92), controlPoint1: CGPoint(x: 19.33, y: 5.18), controlPoint2: CGPoint(x: 19.4, y: 5.55))
            shape.addLine(to: CGPoint(x: 8.12, y: 12.5))
            shape.addCurve(to: CGPoint(x: 4.83, y: 11.2), controlPoint1: CGPoint(x: 7.25, y: 11.7), controlPoint2: CGPoint(x: 6.11, y: 11.2))
            shape.addCurve(to: CGPoint(x: 0, y: 16), controlPoint1: CGPoint(x: 2.16, y: 11.2), controlPoint2: CGPoint(x: 0, y: 13.34))
            shape.addCurve(to: CGPoint(x: 4.83, y: 20.8), controlPoint1: CGPoint(x: 0, y: 18.66), controlPoint2: CGPoint(x: 2.16, y: 20.8))
            shape.addCurve(to: CGPoint(x: 8.12, y: 19.5), controlPoint1: CGPoint(x: 6.11, y: 20.8), controlPoint2: CGPoint(x: 7.25, y: 20.3))
            shape.addLine(to: CGPoint(x: 19.59, y: 26.16))
            shape.addCurve(to: CGPoint(x: 19.46, y: 27.2), controlPoint1: CGPoint(x: 19.51, y: 26.5), controlPoint2: CGPoint(x: 19.46, y: 26.85))
            shape.addCurve(to: CGPoint(x: 24.17, y: 31.87), controlPoint1: CGPoint(x: 19.46, y: 29.78), controlPoint2: CGPoint(x: 21.57, y: 31.87))
            shape.addCurve(to: CGPoint(x: 28.87, y: 27.2), controlPoint1: CGPoint(x: 26.76, y: 31.87), controlPoint2: CGPoint(x: 28.87, y: 29.78))
            shape.addCurve(to: CGPoint(x: 24.17, y: 22.53), controlPoint1: CGPoint(x: 28.87, y: 24.62), controlPoint2: CGPoint(x: 26.76, y: 22.53))
            shape.close()
            shape.move(to: CGPoint(x: 24.17, y: 22.53))
            context.saveGState()
            context.translateBy(x: 23, y: 24)
            shape.usesEvenOddFillRule = true
            UIColor.white.setFill()
            shape.fill()
            context.restoreGState()
            
            context.restoreGState()
        }
        /// facebook-letter-logo
        do {
            context.saveGState()
            context.translateBy(x: 625, y: 256)
            
            /// Capa_1
            do {
                context.saveGState()
                
                // Empty.
                
                context.restoreGState()
            }
            
            context.restoreGState()
        }
        /// instagram
        do {
            context.saveGState()
            context.translateBy(x: 93, y: 571)
            
            /// Capa_1
            do {
                context.saveGState()
                
                /// Shape
                let shape2 = UIBezierPath()
                shape2.move(to: CGPoint(x: 352, y: 0))
                shape2.addLine(to: CGPoint(x: 160, y: 0))
                shape2.addCurve(to: CGPoint(x: 0, y: 160), controlPoint1: CGPoint(x: 71.65, y: 0), controlPoint2: CGPoint(x: 0, y: 71.65))
                shape2.addLine(to: CGPoint(x: 0, y: 352))
                shape2.addCurve(to: CGPoint(x: 160, y: 512), controlPoint1: CGPoint(x: 0, y: 440.35), controlPoint2: CGPoint(x: 71.65, y: 512))
                shape2.addLine(to: CGPoint(x: 352, y: 512))
                shape2.addCurve(to: CGPoint(x: 512, y: 352), controlPoint1: CGPoint(x: 440.35, y: 512), controlPoint2: CGPoint(x: 512, y: 440.35))
                shape2.addLine(to: CGPoint(x: 512, y: 160))
                shape2.addCurve(to: CGPoint(x: 352, y: 0), controlPoint1: CGPoint(x: 512, y: 71.65), controlPoint2: CGPoint(x: 440.35, y: 0))
                shape2.close()
                shape2.move(to: CGPoint(x: 464, y: 352))
                shape2.addCurve(to: CGPoint(x: 352, y: 464), controlPoint1: CGPoint(x: 464, y: 413.76), controlPoint2: CGPoint(x: 413.76, y: 464))
                shape2.addLine(to: CGPoint(x: 160, y: 464))
                shape2.addCurve(to: CGPoint(x: 48, y: 352), controlPoint1: CGPoint(x: 98.24, y: 464), controlPoint2: CGPoint(x: 48, y: 413.76))
                shape2.addLine(to: CGPoint(x: 48, y: 160))
                shape2.addCurve(to: CGPoint(x: 160, y: 48), controlPoint1: CGPoint(x: 48, y: 98.24), controlPoint2: CGPoint(x: 98.24, y: 48))
                shape2.addLine(to: CGPoint(x: 352, y: 48))
                shape2.addCurve(to: CGPoint(x: 464, y: 160), controlPoint1: CGPoint(x: 413.76, y: 48), controlPoint2: CGPoint(x: 464, y: 98.24))
                shape2.addLine(to: CGPoint(x: 464, y: 352))
                shape2.close()
                shape2.move(to: CGPoint(x: 464, y: 352))
                context.saveGState()
                shape2.usesEvenOddFillRule = true
                UIColor.black.setFill()
                shape2.fill()
                context.restoreGState()
                
                /// Shape
                let shape3 = UIBezierPath()
                shape3.move(to: CGPoint(x: 128, y: 0))
                shape3.addCurve(to: CGPoint(x: 0, y: 128), controlPoint1: CGPoint(x: 57.31, y: 0), controlPoint2: CGPoint(x: 0, y: 57.31))
                shape3.addCurve(to: CGPoint(x: 128, y: 256), controlPoint1: CGPoint(x: 0, y: 198.69), controlPoint2: CGPoint(x: 57.31, y: 256))
                shape3.addCurve(to: CGPoint(x: 256, y: 128), controlPoint1: CGPoint(x: 198.69, y: 256), controlPoint2: CGPoint(x: 256, y: 198.69))
                shape3.addCurve(to: CGPoint(x: 128, y: 0), controlPoint1: CGPoint(x: 256, y: 57.31), controlPoint2: CGPoint(x: 198.69, y: 0))
                shape3.close()
                shape3.move(to: CGPoint(x: 128, y: 208))
                shape3.addCurve(to: CGPoint(x: 48, y: 128), controlPoint1: CGPoint(x: 83.9, y: 208), controlPoint2: CGPoint(x: 48, y: 172.1))
                shape3.addCurve(to: CGPoint(x: 128, y: 48), controlPoint1: CGPoint(x: 48, y: 83.87), controlPoint2: CGPoint(x: 83.9, y: 48))
                shape3.addCurve(to: CGPoint(x: 208, y: 128), controlPoint1: CGPoint(x: 172.1, y: 48), controlPoint2: CGPoint(x: 208, y: 83.87))
                shape3.addCurve(to: CGPoint(x: 128, y: 208), controlPoint1: CGPoint(x: 208, y: 172.1), controlPoint2: CGPoint(x: 172.1, y: 208))
                shape3.close()
                shape3.move(to: CGPoint(x: 128, y: 208))
                context.saveGState()
                context.translateBy(x: 128, y: 128)
                shape3.usesEvenOddFillRule = true
                UIColor.black.setFill()
                shape3.fill()
                context.restoreGState()
                
                /// Oval
                let oval = UIBezierPath(ovalIn: CGRect(x: 0, y: 0, width: 34.11, height: 34.11))
                context.saveGState()
                context.translateBy(x: 376.54, y: 101.34)
                UIColor.black.setFill()
                oval.fill()
                context.restoreGState()
                
                context.restoreGState()
            }
            
            context.restoreGState()
        }
        /// TwitterButton
        do {
            context.saveGState()
            context.translateBy(x: 341, y: 364)
            
            /// ShareButton Copy
            do {
                context.saveGState()
                
                // Empty.
                
                context.restoreGState()
            }
            
            /// Circle Copy
            let circleCopy = UIBezierPath(roundedRect: CGRect(x: 0, y: 0, width: 80, height: 80), cornerRadius: 100)
            context.saveGState()
            context.translateBy(x: 171, y: 54)
            UIColor(hue: 0.571, saturation: 0.621, brightness: 0.922, alpha: 1).setFill()
            circleCopy.fill()
            context.restoreGState()
            
            /// Shape
            let shape4 = UIBezierPath()
            shape4.move(to: CGPoint(x: 34.93, y: 3.3))
            shape4.addCurve(to: CGPoint(x: 30.82, y: 4.41), controlPoint1: CGPoint(x: 33.65, y: 3.86), controlPoint2: CGPoint(x: 32.27, y: 4.24))
            shape4.addCurve(to: CGPoint(x: 33.97, y: 0.51), controlPoint1: CGPoint(x: 32.3, y: 3.54), controlPoint2: CGPoint(x: 33.43, y: 2.16))
            shape4.addCurve(to: CGPoint(x: 29.42, y: 2.22), controlPoint1: CGPoint(x: 32.58, y: 1.32), controlPoint2: CGPoint(x: 31.05, y: 1.91))
            shape4.addCurve(to: CGPoint(x: 24.18, y: 0), controlPoint1: CGPoint(x: 28.11, y: 0.85), controlPoint2: CGPoint(x: 26.25, y: 0))
            shape4.addCurve(to: CGPoint(x: 17.02, y: 7.04), controlPoint1: CGPoint(x: 20.23, y: 0), controlPoint2: CGPoint(x: 17.02, y: 3.15))
            shape4.addCurve(to: CGPoint(x: 17.2, y: 8.64), controlPoint1: CGPoint(x: 17.02, y: 7.59), controlPoint2: CGPoint(x: 17.08, y: 8.12))
            shape4.addCurve(to: CGPoint(x: 2.43, y: 1.29), controlPoint1: CGPoint(x: 11.25, y: 8.35), controlPoint2: CGPoint(x: 5.97, y: 5.54))
            shape4.addCurve(to: CGPoint(x: 1.46, y: 4.83), controlPoint1: CGPoint(x: 1.82, y: 2.33), controlPoint2: CGPoint(x: 1.46, y: 3.54))
            shape4.addCurve(to: CGPoint(x: 4.65, y: 10.68), controlPoint1: CGPoint(x: 1.46, y: 7.27), controlPoint2: CGPoint(x: 2.73, y: 9.42))
            shape4.addCurve(to: CGPoint(x: 1.4, y: 9.8), controlPoint1: CGPoint(x: 3.48, y: 10.65), controlPoint2: CGPoint(x: 2.37, y: 10.33))
            shape4.addCurve(to: CGPoint(x: 1.4, y: 9.89), controlPoint1: CGPoint(x: 1.4, y: 9.83), controlPoint2: CGPoint(x: 1.4, y: 9.86))
            shape4.addCurve(to: CGPoint(x: 7.15, y: 16.79), controlPoint1: CGPoint(x: 1.4, y: 13.3), controlPoint2: CGPoint(x: 3.87, y: 16.14))
            shape4.addCurve(to: CGPoint(x: 5.26, y: 17.04), controlPoint1: CGPoint(x: 6.55, y: 16.95), controlPoint2: CGPoint(x: 5.92, y: 17.04))
            shape4.addCurve(to: CGPoint(x: 3.92, y: 16.91), controlPoint1: CGPoint(x: 4.8, y: 17.04), controlPoint2: CGPoint(x: 4.35, y: 16.99))
            shape4.addCurve(to: CGPoint(x: 10.61, y: 21.8), controlPoint1: CGPoint(x: 4.83, y: 19.71), controlPoint2: CGPoint(x: 7.47, y: 21.74))
            shape4.addCurve(to: CGPoint(x: 1.71, y: 24.81), controlPoint1: CGPoint(x: 8.16, y: 23.68), controlPoint2: CGPoint(x: 5.07, y: 24.81))
            shape4.addCurve(to: CGPoint(x: 0, y: 24.71), controlPoint1: CGPoint(x: 1.13, y: 24.81), controlPoint2: CGPoint(x: 0.56, y: 24.78))
            shape4.addCurve(to: CGPoint(x: 10.99, y: 27.87), controlPoint1: CGPoint(x: 3.17, y: 26.71), controlPoint2: CGPoint(x: 6.94, y: 27.87))
            shape4.addCurve(to: CGPoint(x: 31.38, y: 7.85), controlPoint1: CGPoint(x: 24.17, y: 27.87), controlPoint2: CGPoint(x: 31.38, y: 17.15))
            shape4.addCurve(to: CGPoint(x: 31.36, y: 6.94), controlPoint1: CGPoint(x: 31.38, y: 7.55), controlPoint2: CGPoint(x: 31.37, y: 7.24))
            shape4.addCurve(to: CGPoint(x: 34.93, y: 3.3), controlPoint1: CGPoint(x: 32.76, y: 5.95), controlPoint2: CGPoint(x: 33.97, y: 4.71))
            shape4.close()
            shape4.move(to: CGPoint(x: 34.93, y: 3.3))
            context.saveGState()
            context.translateBy(x: 194, y: 80)
            shape4.usesEvenOddFillRule = true
            UIColor.white.setFill()
            shape4.fill()
            context.restoreGState()
            
            context.restoreGState()
        }
        /// FacebookButton
        do {
            context.saveGState()
            context.translateBy(x: 640, y: 408)
            
            /// Circle
            let circle2 = UIBezierPath(roundedRect: CGRect(x: 0, y: 0, width: 80, height: 80), cornerRadius: 100)
            context.saveGState()
            UIColor(hue: 0.612, saturation: 0.593, brightness: 0.588, alpha: 1).setFill()
            circle2.fill()
            context.restoreGState()
            
            /// Shape
            let shape5 = UIBezierPath()
            shape5.move(to: CGPoint(x: 3.81, y: 7.32))
            shape5.addLine(to: CGPoint(x: 3.81, y: 12.52))
            shape5.addLine(to: CGPoint(x: 0, y: 12.52))
            shape5.addLine(to: CGPoint(x: 0, y: 18.89))
            shape5.addLine(to: CGPoint(x: 3.81, y: 18.89))
            shape5.addLine(to: CGPoint(x: 3.81, y: 37.79))
            shape5.addLine(to: CGPoint(x: 11.65, y: 37.79))
            shape5.addLine(to: CGPoint(x: 11.65, y: 18.89))
            shape5.addLine(to: CGPoint(x: 16.9, y: 18.89))
            shape5.addCurve(to: CGPoint(x: 17.63, y: 12.5), controlPoint1: CGPoint(x: 16.9, y: 18.89), controlPoint2: CGPoint(x: 17.39, y: 15.84))
            shape5.addLine(to: CGPoint(x: 11.67, y: 12.5))
            shape5.addLine(to: CGPoint(x: 11.67, y: 8.15))
            shape5.addCurve(to: CGPoint(x: 13.37, y: 6.62), controlPoint1: CGPoint(x: 11.67, y: 7.5), controlPoint2: CGPoint(x: 12.53, y: 6.62))
            shape5.addLine(to: CGPoint(x: 17.64, y: 6.62))
            shape5.addLine(to: CGPoint(x: 17.64, y: 0))
            shape5.addLine(to: CGPoint(x: 11.84, y: 0))
            shape5.addCurve(to: CGPoint(x: 3.81, y: 7.32), controlPoint1: CGPoint(x: 3.62, y: -0), controlPoint2: CGPoint(x: 3.81, y: 6.37))
            shape5.close()
            shape5.move(to: CGPoint(x: 3.81, y: 7.32))
            context.saveGState()
            context.translateBy(x: 31, y: 21)
            shape5.usesEvenOddFillRule = true
            UIColor.white.setFill()
            shape5.fill()
            context.restoreGState()
            
            context.restoreGState()
        }
        
        context.restoreGState()
    }
    
    
    //MARK: - Canvas Images
    
    /// Page 1
    
    class func imageOfDesktop() -> UIImage {
        struct LocalCache {
            static var image: UIImage!
        }
        if LocalCache.image != nil {
            return LocalCache.image
        }
        var image: UIImage
        
        UIGraphicsBeginImageContextWithOptions(CGSize(width: 1024, height: 1024), false, 0)
        FacebookButton.drawDesktop()
        image = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()
        
        LocalCache.image = image
        return image
    }
    
    
    //MARK: - Resizing Behavior
    
    enum ResizingBehavior {
        case aspectFit /// The content is proportionally resized to fit into the target rectangle.
        case aspectFill /// The content is proportionally resized to completely fill the target rectangle.
        case stretch /// The content is stretched to match the entire target rectangle.
        case center /// The content is centered in the target rectangle, but it is NOT resized.
        
        func apply(rect: CGRect, target: CGRect) -> CGRect {
            if rect == target || target == CGRect.zero {
                return rect
            }
            
            var scales = CGSize.zero
            scales.width = abs(target.width / rect.width)
            scales.height = abs(target.height / rect.height)
            
            switch self {
                case .aspectFit:
                    scales.width = min(scales.width, scales.height)
                    scales.height = scales.width
                case .aspectFill:
                    scales.width = max(scales.width, scales.height)
                    scales.height = scales.width
                case .stretch:
                    break
                case .center:
                    scales.width = 1
                    scales.height = 1
            }
            
            var result = rect.standardized
            result.size.width *= scales.width
            result.size.height *= scales.height
            result.origin.x = target.minX + (target.width - result.width) / 2
            result.origin.y = target.minY + (target.height - result.height) / 2
            return result
        }
    }
    
    
}
